### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by cWheme** [The-Gopro336-Archive/Muffin-SRC-BUILDABLE#3]
java.lang.ClassCastException: net.minecraft.client.renderer.texture.TextureManager cannot be cast to me.han.muffin.client.core.mixin.IPatchedTextureManager
	at net.minecraft.client.network.NetHandlerPlayClient.handler$onDisconnect$zck000(NetHandlerPlayClient.java:2312)
	at net.minecraft.client.network.NetHandlerPlayClient.func_147231_a(NetHandlerPlayClient.java)
	at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:354)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1724)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I tried it without my mods but it will crash after some time

**Comment by cWheme** [comment]
Nvm i fixed it
